---
- name: print
  debug:
    msg: "{{ zabbix_repo }}"

- name: Install zabbix repo
  apt:
    deb: "{{ zabbix_repo }}"
    state: present

- name: Install zabbix register dependency
  apt:
    name:
      - python-pip
      - openssl
    state: present
    update_cache: yes

- name: Install zabbix agent "{{ zabbix_version }}"
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes
