---
- name: Install zabbix repo
  apt:
    deb: "{{ zabbix_repo }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"

- name: Install zabbix agent
  apt:
    name:
      - zabbix-agent
      - openssl
    state: present
    update_cache: yes

- name: Install zabbix register dependency
  apt:
    name:
      - python-pip
    state: present
    update_cache: yes
