---
- name: OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Selection OS
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Configure PSK
  import_tasks: psk.yml

- name: Create zabbix scripts directory
  file:
    name: /opt/zabbix
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

# - name: Enable to autoboot
#   service:
#     name: zabbix-agent
#     enabled: True
#     use: service

- name: Register host in zabbix-server
  import_tasks: register.yml
