---
- name: Install repo from zabbix_agent 3
  yum:
    name: "{{ zabbix_repo }}/zabbix-release-{{ zabbix_version }}-1.el7.noarch.rpm"

- name: Install zabbix-agent
  yum:
    name:
      - zabbix-agent
      - openssl
    state: present
    update_cache: yes
